---
# Name your file secrets.yml

development:
  API_HOST: http://localhost:9090
  DB_FILENAME: db/local/dev.db
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'
  GPT_API_KEY: 'your_api_key'
  GOOGLE_CLIENT_KEY: "your_google_client_key"
  SESSION_SECRET: 'run rake new_session_secret'
  REDISCLOUD_URL: url-assigned-by-Redis-rovider-on-Heroku
  
test:
  API_HOST: http://localhost:9090
  DB_FILENAME: db/local/test.db
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'
  GPT_API_KEY: 'your_api_key'
  GOOGLE_CLIENT_KEY: "your_google_client_key"
  SESSION_SECRET: 'run rake new_session_secret'
  REDISCLOUD_URL: url-assigned-by-Redis-rovider-on-Heroku

production:
  API_HOST: ''
  # Assign DATABASE_URL in production
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'
  GPT_API_KEY: 'your_api_key'
  GOOGLE_CLIENT_KEY: "your_google_client_key"
  REDISCLOUD_URL: url-assigned-by-Redis-rovider-on-Heroku
