# frozen_string_literal: true

module LyricLab
  # module ChatGPT
  # TODO put this in the module and in the infrastructure folder

    # line credit calculation methods
    class GptWordProcessorStub
      # hi carrie, you can start to implement the GPT library here

      def initialize()
        # do something
      end

      def extract_words(text)
        # should return a list of unique words extracted by ChatGPT
        text.chars.uniq
      end

      def get_words_metadata(words)
        # should return the metadata of the word generated by ChatGPT
        # in the format
        # {
        #     characters: word,
        #     pinyin: 'pinyin',
        #     translation: 'translation',
        #     word_type: 'word_type',
        #     example_sentence: 'example_sentence'
        #   }
        words.map do |word|
          {
            characters: word,
            pinyin: 'pinyin',
            translation: 'translation',
            word_type: 'word_type',
            example_sentence: 'example_sentence'
          }
        end
      end
    end
  # end
end
